/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface ExplosionMaker {}
  interface GithubCorner {}
  interface ImageGroup {
    'afterLoad': (images: NodeList) => void;
  }
  interface RainbowEffect {}
  interface TextCarousel {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLExplosionMakerElement extends Components.ExplosionMaker, HTMLStencilElement {}
  var HTMLExplosionMakerElement: {
    prototype: HTMLExplosionMakerElement;
    new (): HTMLExplosionMakerElement;
  };

  interface HTMLGithubCornerElement extends Components.GithubCorner, HTMLStencilElement {}
  var HTMLGithubCornerElement: {
    prototype: HTMLGithubCornerElement;
    new (): HTMLGithubCornerElement;
  };

  interface HTMLImageGroupElement extends Components.ImageGroup, HTMLStencilElement {}
  var HTMLImageGroupElement: {
    prototype: HTMLImageGroupElement;
    new (): HTMLImageGroupElement;
  };

  interface HTMLRainbowEffectElement extends Components.RainbowEffect, HTMLStencilElement {}
  var HTMLRainbowEffectElement: {
    prototype: HTMLRainbowEffectElement;
    new (): HTMLRainbowEffectElement;
  };

  interface HTMLTextCarouselElement extends Components.TextCarousel, HTMLStencilElement {}
  var HTMLTextCarouselElement: {
    prototype: HTMLTextCarouselElement;
    new (): HTMLTextCarouselElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'explosion-maker': HTMLExplosionMakerElement;
    'github-corner': HTMLGithubCornerElement;
    'image-group': HTMLImageGroupElement;
    'rainbow-effect': HTMLRainbowEffectElement;
    'text-carousel': HTMLTextCarouselElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface ExplosionMaker {}
  interface GithubCorner {}
  interface ImageGroup {
    'afterLoad'?: (images: NodeList) => void;
  }
  interface RainbowEffect {}
  interface TextCarousel {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'explosion-maker': ExplosionMaker;
    'github-corner': GithubCorner;
    'image-group': ImageGroup;
    'rainbow-effect': RainbowEffect;
    'text-carousel': TextCarousel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'explosion-maker': LocalJSX.ExplosionMaker & JSXBase.HTMLAttributes<HTMLExplosionMakerElement>;
      'github-corner': LocalJSX.GithubCorner & JSXBase.HTMLAttributes<HTMLGithubCornerElement>;
      'image-group': LocalJSX.ImageGroup & JSXBase.HTMLAttributes<HTMLImageGroupElement>;
      'rainbow-effect': LocalJSX.RainbowEffect & JSXBase.HTMLAttributes<HTMLRainbowEffectElement>;
      'text-carousel': LocalJSX.TextCarousel & JSXBase.HTMLAttributes<HTMLTextCarouselElement>;
    }
  }
}


